openapi: "3.1.0"
info:
  title: "SlotsEngine API"
  description: "SlotsEngine API"
  version: "1.0.0"
servers:
  - url: "https://SlotsEngine"
paths:
  /api:
    get:
      summary: "GET api"
      operationId: "indexAction"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ServerVersionMessage"
  /api/load:
    get:
      summary: "GET api/load"
      operationId: "load"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/MachineStateMessage"
  /api/machine-stats:
    get:
      summary: "GET api/machine-stats"
      operationId: "getMachineStats"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/MachineStatsMessage"
  /api/spin/{amount}:
    post:
      summary: "POST api/spin/{amount}"
      operationId: "spin"
      parameters:
        - name: "amount"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/BetResultMessage"
  /api/deposit/{amount}:
    post:
      summary: "POST api/deposit/{amount}"
      operationId: "deposit"
      parameters:
        - name: "amount"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/BalanceMessage"
  /api/withdraw/{amount}:
    post:
      summary: "POST api/withdraw/{amount}"
      operationId: "withdraw"
      parameters:
        - name: "amount"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/BalanceMessage"
components:
  schemas:
    ServerVersionMessage:
      type: "object"
      properties:
        version:
          type: "string"
    MachineStateMessage:
      type: "object"
      properties:
        version:
          type: "string"
        timestampMs:
          type: "integer"
          format: "int64"
        rtp:
          type: "number"
          format: "double"
        betAmount:
          type: "integer"
          format: "int64"
        winAmount:
          type: "integer"
          format: "int64"
        balance:
          type: "integer"
          format: "int64"
        result:
          type: "integer"
          format: "int32"
    LongSummaryStatistics:
      type: "object"
      properties:
        count:
          type: "integer"
          format: "int64"
        sum:
          type: "integer"
          format: "int64"
        min:
          type: "integer"
          format: "int64"
        max:
          type: "integer"
          format: "int64"
    MachineStatsMessage:
      type: "object"
      properties:
        timestampMs:
          type: "integer"
          format: "int64"
        rtp:
          type: "number"
          format: "double"
        betStats:
          $ref: "#/components/schemas/LongSummaryStatistics"
        winStats:
          $ref: "#/components/schemas/LongSummaryStatistics"
    BetResultMessage:
      type: "object"
      properties:
        timestampMs:
          type: "integer"
          format: "int64"
        betAmount:
          type: "integer"
          format: "int64"
        winAmount:
          type: "integer"
          format: "int64"
        balance:
          type: "integer"
          format: "int64"
        result:
          type: "integer"
          format: "int32"
    BalanceMessage:
      type: "object"
      properties:
        balance:
          type: "integer"
          format: "int64"